[build]
  base = "site/"
  command = "yarn build"
  publish = "public"
  environment = { NETLIFY_USE_YARN = "true" }

[functions]
  directory = "../functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200