type Post {
  slug: String!
  claps: Int!
}

type Query {
  findPostBySlug(slug: String!): Post! @resolver(name: "findPostBySlug")
}

type Mutation {
  clapPostBySlug(slug: String!): Post! @resolver(name: "clapPostBySlug")
}
